# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Coveralls; end
module Rocky::Client::StateRequirements; end
module Rocky::Client::StateRequirements; end
